Update Cloudy-V2-05.R add bracket to line 350
A closing bracket was missing from line 350 causing the function to not load into R. 

line 350 before edit =  "if(is.na(threshold){"
line 350 after edit =     "if(is.na(threshold)){"

First error
 Error: unexpected '{' in:
"      # the next few controls are skipped if a threshold is specified (we don't want it to be overruled, even if it's wrong)
      if(is.na(threshold){"

followed by a cascade of errors as a result.